name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: ng build --output-path docs --base-href /ticket-reports/

      - name: Commit build files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "build"
          git push origin gh-pages

      # További lépések, ha szükséges
