name: Build and Deploy to GitHub Pages

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Válaszd ki a számodra megfelelő Node.js verziót

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --output-path docs --base-href /ticket-reports/
